### ISSUE TITLE
Backend repository mentioned in README doesn't exist

### ISSUE THREAD

**Issue by hnchuong** [ntrix/amazin#333]
In README:

```
### Source code

Frontend: [github.com/ntrix/amazin][fenx]

Frontend (old version, MVP Frontend & Backend): [github.com/ntrix/amazin/tree/org-cra][mvp1]

Backend: [github.com/ntrix/amazin-be][bev1]

```

However  github.com/ntrix/amazin-be doesn't exist

**Comment by ntrix** [comment]
Yes,
as said, I'm refactoring the backend part and decided to make it private for a while. I can share it on request but it is not finished yet, and that is not the purpose of this repo.
For learning purposes, there is an MVP version with the backend part (mvp1), which is sufficient for 90% of the API usage.

**Comment by hnchuong** [comment]
Thank you. Your work is greatly helpful. 
If possible, can you share it to me?
